version: "3"
services:
  frontend:
    container_name: my_first_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: hozane/react_web
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - backend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: my_first_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: hozane/express_server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
      - /server/node_modules
